rust-lang/bors

Cargo.lock
Cargo.toml
src/bin/bors.rs
src/command/mod.rs
src/command/parser.rs
src/config.rs
src/github/mod.rs
src/github/webhook.rs
src/lib.rs

The server doesn't really do anything yet, it just parses and validates GitHub webhooks.

Add `bors` binary with basic GitHub webhook parsing

---

src/bin/bors.rs
src/github/api.rs
src/github/service.rs
src/github/webhook.rs

As suggested by @pietroalbini.

Reload repositories whenever an installation changes

---

src/bors/command/parser.rs

This PR modifies the parser to handle key value pairs

Modify parser to handle key value pairs

---

src/bors/command/mod.rs
src/bors/command/parser.rs
src/bors/handlers/mod.rs
src/bors/handlers/trybuild.rs
src/github/mod.rs
src/github/webhook.rs
src/tests/state.rs

Fixes: https://github.com/rust-lang/bors/issues/23
CC @sladyn98

Add the option to select a parent for a try build

---

src/github/api/mod.rs

While it's not bad to have a loud error, we shouldn't stop refreshing repositories when one of them fails to load.

Do not abort repository loading when a repo cannot be loaded

---

Dockerfile

This should help producing better backtraces in production.

Build binary in the Docker with debug symbols

---

src/bors/handlers/trybuild.rs
src/bors/mod.rs
src/github/api/client.rs
src/github/api/mod.rs
src/github/api/operations.rs
src/tests/database.rs
src/tests/state.rs

feat: display workflow url

---

src/bin/bors.rs
src/bors/handlers/mod.rs
src/bors/mod.rs
src/github/api/mod.rs
src/github/server.rs
src/lib.rs

Various small bits of cleanup. I didn't get very far, but I want to merge it soon to avoid conflicting later.

Small cleanup

---

.github/workflows/test.yml

So that we can enable merge queue on this repository. CC @jdno

CI: add `merge_group` workflow trigger

---

src/github/api/mod.rs

Cause installation client couldn't be used to load app info

fix: load app with app client

---

src/github/api/mod.rs

The code wasn't using pagination before, and it was unnecessarily accessing `installation.repositories_url`. If this URL ever points to somewhere else than GitHub, octocrab will fail the request anyway, so we might as well just hardcode the API path.
CC @vohoanglong0107

Add pagination when loading installation repositories

---

docs/development.md

Bors also need to listen to `Workflow run` event

docs: add necesarry webhook event to test bors

---

src/bors/handlers/refresh.rs
src/permissions.rs
src/tests/state.rs

Just want to get those complaints out of my editor 🥹

fix: clippy lint

---

src/bors/handlers/mod.rs

This span turns the handler into non Send future, which disables the ability to run handlers concurrently.

fix: span hold accross await point

---

docs/development.md

Add `cargo` prefix to `sqlx` commands

---

.github/workflows/deploy.yml

So that merges are automatically deployed to a staging environment.

Deploy to staging from the main branch

---

src/bin/bors.rs
src/bors/context.rs
src/bors/handlers/mod.rs
src/bors/handlers/refresh.rs
src/bors/mod.rs
src/github/api/client.rs
src/github/api/mod.rs
src/lib.rs
src/permissions.rs
src/tests/mocks/mod.rs
src/tests/mocks/repository.rs
src/tests/mod.rs
src/tests/permission.rs
src/tests/state.rs
src/tests/tester.rs

Follow up on https://github.com/rust-lang/bors/pull/94, this PR adds a mock server for team API

tests: mock team api

---

src/bin/bors.rs

Temporary code to reset the DB on production (this is the easiest way to do it that I know of, sadly).

Reset DB on production

---

src/bors/handlers/ping.rs
src/tests/mocks/bors.rs
src/tests/mocks/comment.rs
src/tests/mocks/github.rs
src/tests/mocks/mod.rs
src/tests/mocks/pull_request.rs
src/tests/mocks/repository.rs

Implement comment checking in tests

---

src/github/webhook.rs

To prevent stack overflow in dev

refactor: split webhook parser to multiple function

---

src/bors/event.rs
src/bors/handlers/mod.rs
src/bors/handlers/review.rs
src/github/webhook.rs
src/tests/mocks/bors.rs
src/tests/mocks/mod.rs
src/tests/mocks/pull_request.rs

This is homu's default behavior

feat: unapprove on PR's base changed

---

src/bors/handlers/review.rs

Also use name instead of SHA base on suggestion

fix: use base instead of head for base changed notification

---

.github/renovate.json5

discussed in https://github.com/rust-lang/bors/pull/132#issuecomment-2326727861

chore(renovate): disable docker updates

---

Dockerfile

GitHub Actions complain about this in other PRs

chore: fix style of Dockerfile

---

.github/workflows/deploy.yml

Otherwise the job fails on fork. E.g.:
Link of the fork of the screenshot: https://github.com/MarcoIeni/bors

chore: don't deploy if fork

---

docs/development.md

Document how to run tests

---

Cargo.lock
Cargo.toml
src/github/api/mod.rs
src/tests/mocks/comment.rs

EDIT: tests are failing. the regression is introduced in 0.39

chore: update octocrab to version 0.42

---

docs/development.md

Close https://github.com/rust-lang/bors/issues/177

docs: document how to see logs in tests

---

Cargo.lock
Cargo.toml

I updated this manually because renovate has issues with this PR, I don't know why
See https://github.com/rust-lang/bors/pull/171

chore(deps): update thiserror to version 2

---

src/bors/handlers/review.rs
src/tests/mocks/bors.rs

Add universal synchronization in tests

---

Cargo.toml
docs/development.md

And also add a note about using LLD.

Improve compilation performance

---

src/database/operations.rs

I didn't know how to do it before, but I found the right syntax now.

Use `sqlx::Encode` implementation for `GithubRepoName`

---

.github/workflows/test.yml
Cargo.toml
Dockerfile
src/bin/bors.rs
src/bors/context.rs
src/bors/handlers/help.rs
src/bors/handlers/mod.rs
src/bors/handlers/pr_events.rs
src/bors/handlers/refresh.rs
src/bors/handlers/review.rs
src/bors/handlers/trybuild.rs
src/bors/handlers/workflow.rs
src/bors/mod.rs
src/config.rs
src/github/api/client.rs
src/github/api/mod.rs
src/github/api/operations.rs
src/github/mod.rs
src/github/server.rs
src/github/webhook.rs
src/lib.rs
src/tests/mocks/app.rs
src/tests/mocks/bors.rs
src/tests/mocks/comment.rs
src/tests/mocks/github.rs
src/tests/mocks/mod.rs
src/tests/mocks/permissions.rs
src/tests/mocks/pull_request.rs
src/tests/mocks/repository.rs
src/tests/mocks/workflow.rs

chore: Update crate to Edition 2024

---

Cargo.lock
Cargo.toml
src/bors/mod.rs
src/github/api/client.rs
src/github/api/mod.rs
src/github/api/operations.rs
src/utils/timing.rs

Handle Github API timeouts

---

src/bin/bors.rs
src/bors/event.rs
src/bors/handlers/mod.rs
src/bors/handlers/refresh.rs
src/bors/mod.rs
src/tests/mocks/bors.rs

This allows us to configure the interval for each thing that should be refreshed separately.

Split refresh handlers

---

src/github/server.rs
src/templates.rs
templates/not_found.html

Add 404 not found page

---

src/bors/comment.rs
src/bors/handlers/trybuild.rs
src/bors/handlers/workflow.rs

Suggested in [#t-infra/bors > slightly larger try message](https://rust-lang.zulipchat.com/#narrow/channel/496228-t-infra.2Fbors/topic/slightly.20larger.20try.20message/with/521355755).

Make try build comments more compact

---

src/bors/command/parser.rs
src/bors/handlers/mod.rs
src/bors/handlers/review.rs
src/bors/handlers/trybuild.rs

close https://github.com/rust-lang/bors/issues/289

suggest how to cancel try job

---

src/bors/command/parser.rs
src/bors/comment.rs
src/bors/handlers/trybuild.rs

Found [here](https://github.com/rust-lang/rust/pull/141927#issuecomment-2937319688).

Use correct bot prefix in try build in progress comment

---

src/bors/handlers/refresh.rs
src/tests/mocks/bors.rs

There's some old code that utilises assertions where it could be updated to use `.wait_for_pr(...)`.

Replace asserts with `.wait_for_pr`

---

src/database/mod.rs

Add doc comments to database model fields

---

.sqlx/query-33cf1b803a0b658f197ab26d87e2c6c4fe42128cb481a234372626f35392e809.json
src/bors/handlers/refresh.rs
src/bors/handlers/trybuild.rs
src/bors/handlers/workflow.rs
src/database/client.rs
src/database/mod.rs
src/database/operations.rs
src/github/api/client.rs
src/github/api/operations.rs
src/tests/mocks/bors.rs
src/tests/mocks/repository.rs

We should have the proper permissions now (thanks Marco!), both on staging and production.
CC @Sakib25800

Re-enable PR checks

---

src/github/api/mod.rs
src/github/server.rs

This has been bugging me for a while in logs, it was quite hard to read.

Remove multi-line logs

---

src/bors/comment.rs
src/bors/handlers/review.rs

Noticed while testing the merge queue.

Forbid unapproving closed PRs

---

src/bors/handlers/mod.rs

Before it wouldn't work on staging.

Generalize bors prefix override

---

src/bors/handlers/pr_events.rs
src/bors/handlers/refresh.rs
src/bors/merge_queue.rs
src/tests/mocks/bors.rs
src/tests/mocks/github.rs
src/tests/mocks/repository.rs

Fix flakiness of `enqueue_prs_on_pr_opened` and log received comments in tests.

Fix flakiness of `enqueue_prs_on_pr_opened`

---

src/bors/merge_queue.rs
src/tests/mocks/pull_request.rs

- Add sanity checks before starting an auto build

Add merge queue sanity checks

---

src/bors/handlers/info.rs
src/bors/handlers/mod.rs
src/bors/handlers/review.rs
src/bors/handlers/trybuild.rs
src/bors/merge_queue.rs
src/bors/mod.rs
src/database/mod.rs
src/github/api/operations.rs
src/github/mod.rs

- Unify the separates auto and try attempt merge functions

Unify `attempt_merge()`
