rust-lang/bors

src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/bors/mod.rs, src/github/api/client.rs, src/github/webhook.rs, src/tests/github.rs, src/tests/state.rs
Before, the SHA was taken out of `pr.base.sha`, but that commit SHA might not be updated.
=> Resolve actual SHA of PR base branch

Dockerfile
The current rust version in Dockerfile is too old, make it incompatible with cargo chef
=> chore: bump rust version in Dockerfile

database/entity/src/build.rs, database/migration/src/lib.rs, database/migration/src/m20240312_053916_add_parent_to_build.rs, src/bors/command/mod.rs, src/bors/command/parser.rs, src/bors/handlers/trybuild.rs, src/database/mod.rs, src/database/sea_orm_client.rs, src/tests/state.rs
Implement `@bors try parent=last`, to use the last build parent as base.
Will post a comment to explain if no last build was found, and postpone.
Fixes: https://github.com/rust-lang/bors/issues/29
=> feat: try last parent

.github/workflows/test.yml, Dockerfile
The bot now fails in Docker (wrong `OpenSSL` version), this should help catch issues like this in the future.
=> Add test for running the Docker image on CI

src/bors/handlers/refresh.rs, src/bors/mod.rs, src/github/api/client.rs, src/github/api/mod.rs, src/tests/state.rs
=> feat: reload config

src/bors/handlers/trybuild.rs, src/github/mod.rs, src/github/webhook.rs, src/permissions.rs, src/tests/event.rs, src/tests/permissions.rs, src/tests/state.rs
=> feat: use user id instead of username

src/github/server.rs
For now, bors does not perform any locking of per-repository GitHub API operations, which share a common resource (e.g. the try branches). This means that it is open to race conditions. Until such locking is introduced, we should handle commands serially.
The code is now prepared for concurrent execution (with `Arc`s etc.), so disabling/enabling concurrency is a matter of such a one-line change, which is great.
=> Temporarily disable concurrency of bors

src/bors/comment.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/bors/mod.rs
Fixes #58
We have much more unique comment than we do metadata, so instead of a dedicated Comment Struct for each type of comments, I created a Metadata struct for each type of Metadata
=> feat: add metadata to comment

src/bors/handlers/mod.rs, src/bors/mod.rs, src/github/api/client.rs, src/github/api/mod.rs, src/tests/state.rs
An effort to clean up the blur between global and per repo state
=> refactor: move is_internal_comment to per repo

src/bors/handlers/mod.rs
Fix #66 
By comparing the set of repositories before reloading and the set of repositories got from reloading, I could infer which repository was reloaded, which was not and which was recently added.
I tried to add tests to verify this behavior but was limited by our current tests infra. It was hard to load more than one repo during reloading due to the way we are mocking the `RepositoryLoader`.
The refresh process of each repository (config refreshing, etc...) is already granular, and each refresh task run concurrently with the other using `tokio::join!`. Therefore, no further action is needed in this regard.
=> feat: make refresh more robust

src/bors/command/mod.rs, src/bors/command/parser.rs, src/bors/handlers/mod.rs, src/bors/handlers/trybuild.rs
Fixes #80 
It works on my branch 🤣
https://github.com/vohoanglong0107/test-bors/commit/9eeaa0c106c10810b5e7bf77540a1a4ab26e6e84
=> feat: arbitrary try build

docker-compose.yaml
I don't think that we need health checks, and the volume was not working for me locally. Explicit volume should not be needed, `docker-compose up` should remember the latest state, unless you clear docker temporary artifacts.
CC @vohoanglong0107
=> Simplify docker-compose.yml

Cargo.lock, Cargo.toml, src/bors/handlers/ping.rs, src/tests/mocks/app.rs, src/tests/mocks/mod.rs, src/tests/mocks/repository.rs, src/tests/mocks/user.rs, src/tests/mod.rs, src/tests/tester.rs
This PR initiates the HTTP mocking implementation mentioned in #93, by mocking the following route:
- GET /app
- GET /app/installations
- GET /installation/repositories
- POST /app/installations/{...}/access_tokens
- GET /repos/{owner}/{name}/contents/rust-bors.toml
I'd like to include team permission retrieval in this PR as well, but since it will involve some degree of refactoring, it's worth a dedicated PR in my opinion.
=> tests: mock app and repositories retrieval

.github/workflows/test.yml
Just to make sure that there are no post-monomorphization surprises
=> Run `cargo build` instead of `cargo check` in CI

src/bors/handlers/ping.rs, src/database/client.rs, src/tests/mocks/comment.rs, src/tests/mocks/mod.rs, src/tests/mocks/pull_request.rs, src/tests/mocks/repository.rs, src/tests/mocks/user.rs
This PR implements mocking for the following endpoints:
- GET /repos/{owner}/{name}/pulls/{number}
- POST /repos/{owner}/{name}/issues/{number}/comments
With this, we can now test bors using the comment webhook.
=> test: mock comment creation api

docker-compose.yaml
So that it matches the version that we currently use in the deployment environment.
=> Change Postgres to 15.5

src/bors/handlers/mod.rs, src/bors/handlers/refresh.rs, src/bors/mod.rs, src/github/api/client.rs, src/github/api/mod.rs, src/github/api/operations.rs
We currently have several methods to retrieve the repository name, which makes it a little bit confusing when deciding which one to use. This PR clean them up and adjust some visibility modifier along the way.
=> refactor: unify ways to get repository name

.github/workflows/deploy.yml
This PR adds a CI job for deploying the bot to production. It works like this:
1) After a push to `main`, the bot is automatically deployed to the `staging` environment (this was pre-existing)
2) After a push to `main`, a workflow for deploying the bot to the `production` environment is started. This environment should be (manually) configured in this repo, so that it needs a review from someone (a bors admin, or multiple people).
The deployment history can be seen at https://github.com/rust-lang/bors/deployments, where admins can also approve the deployments.
Note that I have just copy-pasted the job from the staging environment for now. I'm not actually sure what should be changed to switch from staging to production - probably this: `arn:aws:iam::392478027976:role/gha-access`? I found …
=> Add a CI job for deploying to production

src/bors/event.rs
The global event variant is rarely used (compare to the per repository event), so there won't be much improvement if we try to fix this.
=> fix: ignore clippy warning on variant's size

.github/renovate.json5
Close #153 
This should prevent Cargo.lock updates from `a.b.c` to `a.b.(c+1)`.
From my understanding, unfortunately disabling `minor` as well means that we'll stop get updates from `0.x.y` to `0.(x+1).0`, so I haven't disabled minor.
However ideally we want to disable updates from `a.b.c` to `a.(b+1).0`. Maybe something we can investigate further in the future.
=> chore(renovate): don't update patches

.github/renovate.json5
Related to https://github.com/rust-lang/bors/pull/154#issuecomment-2361009772
Tested in https://github.com/MarcoIeni/renovate-playground/pull/12
I already edited the required github setting
=> chore(renovate): enable security updates

Cargo.lock, Cargo.toml, src/bin/bors.rs, src/github/api/mod.rs, src/github/webhook.rs, src/tests/mocks/github.rs
I diffed the actual crates.io contents via
```bash
curl -L https://crates.io/api/v1/crates/secrecy/${VERSION}/download | tar -xf -
```
with `VERSION` as `0.8.0` and `0.10.3`, then
diffing via git. It revealed nothing suspicious,
with changes as claimed per their CHANGELOG.md.
0.10.0 had some breaking changes. `Secret<T>` is
no longer a thing, instead there's `SecretBox<T>`. It turned out secrecy usage in bors is limited,
and private keys are fed as PEM-encoded `String`s. For this, there's `SecretString`, which is just an alias for `SecretBox<str>`. Accepting it and
converting to bytes in `create_github_client`
simplifies code at the call sites a bit.
=> chore(deps): update secrecy 0.8.0 -> 0.10.3

.github/workflows/test.yml
It shouldn't be needed, since we use merge groups.
=> Do not run CI on the `main` branch

.github/workflows/test.yml, Dockerfile, src/tests/util.rs
Here's why I chose `actions-rust-lang/setup-rust-toolchain`:
- automatically setup `Swatinem/rust-cache@v2`.
- respects `rust-toolchain` file in case we add it in the future
- it has a [problem matcher](https://github.com/actions-rust-lang/setup-rust-toolchain/blob/main/rust.json)
- it has the `toolchain` field, which decouples the version of the action from the rust toolchain version. I.e. I think `action/action@stable` isn't great, because you can't pin the action commit.
=> chore(ci): remove deprecated actions-rs actions

src/bin/bors.rs, src/bors/comment.rs, src/bors/handlers/mod.rs, src/bors/handlers/trybuild.rs, src/bors/mod.rs, src/github/api/client.rs, src/github/api/mod.rs, src/github/server.rs, src/lib.rs
Previously RepositoryLoader was created to ease the migration from trait to sqlx. Now that the migration is complete, we can safely clean it up.
=> refactor: clean up RepositoryLoader

src/bors/event.rs, src/bors/handlers/workflow.rs, src/config.rs, src/github/webhook.rs
Fixes: https://github.com/rust-lang/bors/issues/84
I have added a serilazed min_ci_duartion field which takes care that atleast 60 seconds of testing is being done.
=> feat: added min duaration checking in RepositoryConfig

src/bors/handlers/help.rs
Before, it was a static string and it was easy to forget to add new commands to it. After this change, it should be more difficult to forget to modify help.
You can see the current help output in action [here](https://github.com/Kobzol/bors-kindergarten/pull/13#issuecomment-2535935849).
This pull request was created in cooperation with students of the [Rust subject](https://github.com/Kobzol/rust-course-fei) on the VSB-TUO university.
=> Generate help dynamically

Cargo.lock, Cargo.toml, src/github/webhook.rs
Changes: https://github.com/tokio-rs/axum/releases/tag/axum-v0.8.0
This is the biggest breaking change:
> breaking: Upgrade matchit to 0.8, changing the path parameter syntax from /:single and /*many to /{single} and /{*many}; the old syntax produces a panic to avoid silent change in behavior (https://github.com/tokio-rs/axum/pull/2645)
but I haven't seen this used in the codebase
=> chore: update to axum 0.8

.github/workflows/test.yml
It was trying to use a dependency that was already on edition 2024.
=> Respect lockfile of `sqlx-cli` in CI

src/bors/handlers/mod.rs, src/tests/mocks/pull_request.rs, src/tests/mocks/repository.rs
=> fix: ignore unrelated comments

src/bors/handlers/review.rs, src/bors/handlers/trybuild.rs, src/tests/mocks/repository.rs, src/tests/mocks/user.rs
=> Improve tests regarding permissions

.gitignore, .sqlx/query-2eaf959d9345ee1d1baf5453b693f0914014029977243d15ef233e8fba49f2d5.json, src/bors/command/mod.rs, src/bors/command/parser.rs, src/bors/handlers/help.rs, src/bors/handlers/info.rs, src/bors/handlers/mod.rs, src/database/client.rs, src/database/operations.rs
Fixes: https://github.com/rust-lang/bors/issues/213
=> @bors info command

.sqlx/query-6a911b59abd89bdb10e283902ea3a08c483e5a6238344c7ac969a0602674e888.json, .sqlx/query-6d68067c7121438630d77590ed644d4bc654978836fe5ceda2f0041aeba68e64.json, migrations/20250304172534_add_repository_model.down.sql, migrations/20250304172534_add_repository_model.up.sql, src/bors/command/mod.rs, src/bors/command/parser.rs, src/bors/event.rs, src/bors/handlers/help.rs, src/bors/handlers/mod.rs, src/bors/handlers/review.rs, src/database/client.rs, src/database/mod.rs, src/database/operations.rs, src/github/webhook.rs, src/permissions.rs, src/tests/mocks/comment.rs, src/tests/mocks/pull_request.rs, src/tests/mocks/repository.rs
Fixes: https://github.com/rust-lang/bors/issues/207
=> Tree Closing and Opening

.sqlx/query-cc7019b45037e155c4ce8f0bad9df0dcbe339fb59f93aec8bb6d34719ee042d3.json, src/database/mod.rs, src/database/operations.rs
I realized in https://github.com/rust-lang/bors/pull/226 that we can do this in a more idiomatic way.
=> Refactor storage of `TreeState` in the DB

.gitignore, .sqlx/query-44415582f7be15fa152e086db4e664a82180544d4152e616a77f5e50f9d75145.json, .sqlx/query-66b7cb451d49e670d814d89d2a66ba3dd5df162984ca29dfdb1e893b1afca7ce.json, .sqlx/query-b7827a8eb8b11c8d6751498aba4d62c28372f666fec43294ebe94dabf0f46923.json, .sqlx/query-eba0377c0959404d5d208aae9763a92186f2a784639b87661f4d1ce68cc995ea.json, .sqlx/query-fdb7f932af60a3c579516e8ff8ed3866cce4fd88b2f41f78a5ddaa2489e796fb.json, migrations/20250315140840_add_merge_state_to_pr.up.sql, migrations/20250315140840_add_merge_to_pr.down.sql, src/bors/event.rs, src/bors/handlers/info.rs, src/bors/handlers/mod.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/review.rs, src/bors/handlers/trybuild.rs, src/database/client.rs, src/database/mod.rs, src/database/operations.rs, src/github/mod.rs, src/github/webhook.rs, src/tests/mocks/bors.rs, src/tests/mocks/mod.rs, src/tests/mocks/pull_request.rs, tests/data/webhook/security-advisory-published.json
Related issue: #218 
This PR tracks merge ability. It adds a new column: `merge_state`. 
**Homu Implementation**
- Mergeable status is tracked via the `mergeable` column in the `pull` table
- **On PR open / reopen / edit / push**: `mergeable` is set to `None` 
- **On PR edit**: `mergeable` is set to `None`  only if base branch has changed
- **On branch push event**: 
- All PRs targeting the given branch have `merge_state` set to `None`
- If still null, then wait 5s 
- If still null, then add to queue 
- **Async**: all PRs with a `mergeable` of `None` are scheduled to refetch in a background task via a queue
**Proposed Implementation**
- Mergeable status is tracked via the `merge_state` column in the `pull_request` table
- **On PR open / reopen / push**: `merge_state` is set to `unknown` …
=> feat: track mergeability 

Cargo.toml, src/bors/handlers/trybuild.rs, src/utils/mod.rs, src/utils/text.rs
=> Prevent spam from GitHub mentions in merge commits

docs/development.md, tests/data/migrations/20240517094752_create_build.sql, tests/data/migrations/20240518024921_create_pr.sql, tests/data/migrations/20240518024946_create_workflow.sql, tests/data/migrations/20240626072340_add_approved_by_to_pr.sql, tests/data/migrations/20250227095730_add_priority_to_pr.sql, tests/data/migrations/20250304150656_add_delegated_to_pr.sql, tests/data/migrations/20250304172534_add_repository_model.sql, tests/data/migrations/20250307150834_add_rollup_to_pr.sql, tests/data/migrations/20250311143621_add_approved_sha_to_pr.sql, tests/data/migrations/20250313013946_add_base_branch_to_pr.sql, tests/data/migrations/20250315140840_add_merge_state_to_pr.sql, tests/data/migrations/20250318120405_add_pr_status.sql, tests/data/migrations/20250324151905_rename_delegated_to_delegated_permission.sql, tests/data/migrations/20250331142635_add_pr_status_index.sql, tests/migrations.rs
Fixes #257 
This PR adds tests that incrementally populate the database with test data for every migration.
=> Add database migrations population tests

migrations/20250304172534_add_repository_model.up.sql
For consistency with the rest of the migrations.
=> Add `IF NOT EXISTS` to repository creation migration

src/tests/mocks/mod.rs
Workflows are cancelled in parallel, so we should not depend on any specific order here.
=> Make check for cancelled workflows deterministic

.sqlx/query-07ad0343b05020b1df6f21b8863ad848f096688a8e41e74f9481e1c27b381bb9.json, src/bors/handlers/mod.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/refresh.rs, src/database/client.rs, src/database/operations.rs, src/github/server.rs
Fixes #218 
This PR:
- Adds mergeable queue processing on periodic refresh
=> Implement refresh mechanism for unknown mergeable PRs 

src/bors/handlers/info.rs, src/bors/handlers/mod.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/review.rs, src/bors/handlers/trybuild.rs, src/database/client.rs, src/tests/mocks/bors.rs
Related #218 
This PR adds to the mergeable queue on:
- PR open
- PR reopen
- Push to PR
=> Add to mergeable queue on PR push, open and reopen

.sqlx/query-711316962e9434e549af5de738de2b415d0ccdfd4f134a21e69a42adbc6c8aae.json, Cargo.lock, Cargo.toml, src/bin/bors.rs, src/bors/event.rs, src/bors/handlers/mod.rs, src/bors/handlers/refresh.rs, src/bors/mod.rs, src/database/client.rs, src/database/operations.rs, src/github/api/client.rs, src/github/mod.rs, src/tests/mocks/bors.rs, src/tests/mocks/pull_request.rs, src/tests/mocks/repository.rs
=> Synchorize pr state periodically

src/bors/handlers/refresh.rs
=> Fix flaky test `refresh_pr_with_status_closed`

Cargo.lock, Cargo.toml, Dockerfile, src/bin/bors.rs, src/database/mod.rs, src/github/server.rs, src/github/webhook.rs, src/lib.rs, src/templates.rs, src/tests/mocks/bors.rs, templates/index.html
This PR adds the website's home page, where it displays the repos. It also displays "[TREECLOSED]" is the tree is closed for the corresponding repo. 
The HTML is essentially the same as it was 11 years ago with slight differences:
- Homu -> Bors
- The section on "Customizing the Queue's Contents" has not been added as that will be added when the /queue is added and I don't know if all of the mentioned features are going to be supported
- The commands shown in the home page do not completely match as either some are not yet handled by bors just yet (e.g. `force` command) or some have been removed (e.g. `r=<name>`)
=> Bootstrap website

src/bors/comment.rs, src/bors/handlers/trybuild.rs
Implements the change discussed in https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Transitioning.20try.20builds.20to.20new.20bors/with/523051102.
=> Cancel previously running try build on `@bors try`

templates/queue.html
Adds the remaining columns for the queue page, including:
- Title
- Author
- Assignees
and some table spacing to make it easier to parse.
=> Add remaining columns to queue page

src/bors/handlers/mod.rs, src/bors/handlers/refresh.rs, src/bors/handlers/trybuild.rs, src/bors/mod.rs, src/tests/mocks/bors.rs, src/tests/util.rs
This should hopefully fix the spurious errors that we have been seeing with `refresh_cancel_workflow_after_timeout`.
CC @Sakib25800
=> Drain previously seen notifications in `TestSyncMarker`

src/bin/bors.rs
So that you can easily click on the link in terminal when bors starts up.
=> Add http to link printed by bors

src/bors/handlers/refresh.rs, src/bors/mergeable_queue.rs
I had forgotten to use `.enqueue_now(...)` rather than `.enqueue(...)`.
Since the purpose of the mergeable queue refresh event is to catch missed PRs, we know that time has already elapsed, so we can enqueue immediately.
=> Use `.enqueue_now(...)` for mergeable queue refresh event

src/bors/handlers/pr_events.rs
- There are some comments that jump to the next line early and I've removed them (assuming they were unintentional)
- For the PR push needing re-approval comment, I have removed the backticks to allow for GitHub's SHA link formatting to work
=> Fix PR comment formatting

.sqlx/query-02da9f6b50aedf8ccca20aa166c04e7406180ec882d79a0c5d5961779894a6f0.json, .sqlx/query-1b2604805b896aead48b3f56ddefbe045ade285f5886ee3b0291c403293ad236.json, .sqlx/query-3107d965f4602e40a60f856dda74ed7cc57f40071bad913011db294e90d6859b.json, .sqlx/query-33cf1b803a0b658f197ab26d87e2c6c4fe42128cb481a234372626f35392e809.json, .sqlx/query-35e097f1dd2bcfe944c09c789426aa5716b90dc1b91de17629b158dd36eee7d9.json, .sqlx/query-367bf2de86a8a92b56b2be296cef119a7835ab5fd09326265a4a1403d0d6ad19.json, .sqlx/query-483efa3070e78c109d493533ca114433d1228427b35742760521487a9bc0be51.json, .sqlx/query-62763d313a8278147d0f6fea3dd3d945e77bbdcf50e3fcfba029f24ce7481618.json, .sqlx/query-7c02e94615e2ac8d8ea1d45b7b21a3dc29b884f514131df60aeb63569568e82f.json, .sqlx/query-92a82f32ea1f0ae952e7f0a116b473893358292541fd507ebd381138901ae48a.json, .sqlx/query-a146064228559bca97e795319590ddeb83e3a97562c6330fe72375bfc3cadfd3.json, migrations/20250702100259_add_check_run_id_to_build.down.sql, migrations/20250702100259_add_check_run_id_to_build.up.sql, src/bors/handlers/refresh.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/database/client.rs, src/database/mod.rs, src/database/operations.rs, src/github/api/client.rs, src/github/api/operations.rs, src/tests/mocks/bors.rs, src/tests/mocks/repository.rs, tests/data/migrations/20250702100259_add_check_run_id_to_build.sql
Fixes half of #322 
This PR adds the dots and a title: "Bors try build". No detail or text is added to the check run UI. 
The check run is added to the PR head and starts off in pending -> error / success. 
Success: https://github.com/Sakib25800/rust/pull/424
Fail: https://github.com/Sakib25800/rust/pull/425
Before merging the try build we could also set `CheckRunStatus` to `CheckRunStatus::Queued` but I think the window is so small it's not worth adding and no one is going to notice.
=> Add try build check run

.github/workflows/deploy-production.yml, .github/workflows/deploy-staging.yml
Change prod deployments to not being triggered automatically anymore.
Deployments can be manually requested on demand.
We have Deployments reviews setup, so another member of the bors team or an infra-admin can approve the deployment.
This also prevents people from self-approving deployments because the workflow_dispatch is triggered from the user, not from the github actions bot. See [#t-infra > Migrating bors try to new bors @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Migrating.20bors.20try.20to.20new.20bors/near/528520590)
=> ci: trigger production deployment manually

src/bors/comment.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/bors/mod.rs, src/github/api/client.rs, src/github/api/operations.rs, src/tests/mocks/mod.rs, src/tests/mocks/repository.rs, src/tests/mocks/workflow.rs, src/utils/text.rs, src/utils/timing.rs
As noted [here](https://github.com/rust-lang/bors/issues/356#issuecomment-3090121768), it takes a while to load the jobs on rust-lang/rust. I'll be observing how it works on production and if it's problematic, I'll remove this functionality.
Fixes: https://github.com/rust-lang/bors/issues/356
=> Show a sample of failed jobs when a build fails

src/bin/bors.rs, src/bors/comment.rs, src/bors/context.rs, src/bors/handlers/mod.rs, src/bors/handlers/review.rs, src/tests/mocks/bors.rs
This will need configuration in simpleinfra (https://github.com/rust-lang/simpleinfra/pull/752).
=> Configure web URL for bors and show it in approved commit message

src/tests/mocks/bors.rs
When I changed the error reporting here last week, I was telling to myself: "the errors are not super nice here, maybe I could improve them.. no, it will be fine, this doesn't crash often". Well :)
Should help with https://github.com/rust-lang/bors/pull/330.
CC @Sakib25800
=> Make error message nicer when bors service panics in tests

src/bors/command/parser.rs, src/bors/handlers/mod.rs
Bors part of https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Migrating.20bors.20try.20to.20new.20bors/with/528288215.
=> Parse `@bors try` commands to replace homu for try builds

.sqlx/query-3ae0ba7ce98f0a68b47df52a9181134df3ac7818af0c085ac432eb52874a62a2.json, rust-bors.example.toml, src/bors/comment.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/review.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/bors/merge_queue.rs, src/bors/mod.rs, src/config.rs, src/database/client.rs, src/database/operations.rs, src/github/labels.rs, src/tests/mocks/bors.rs, src/tests/mocks/comment.rs, src/tests/mocks/mod.rs, src/tests/mocks/pull_request.rs, src/tests/mocks/repository.rs, src/utils/sort_queue.rs
This PR adds the complete merge queue process from auto build -> merge to master. 
The merge queue works like so: 
- Every 30s `handle_merge_queue(...)` is called
- It selects a PR that can be merged (based on a set of merge queue priority rules)
- As part of the sorts, successful auto builds come first and pending ones second and a bunch of other rules. But those are 
the two most important. 
- If `handle_merge_queue(...)` sees:
- Successful auto build, it will merge it 
- Pending auto build, it will halt the queue until the auto build is done (to prevent simultaneous auto builds)
- From the check suite completed webhook, we attempt to `try_complete_build(...)` where we attempt to determine the build status and post relevant comments
Homu works in exactly the same way, with the only …
=> Merge queue

src/bors/comment.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/review.rs
- Adds PR #326 tests. 
- Closes #369 
Also slips in a change from cooked to raw string literal for the auto build success comment.
=> Add auto build cancel tests

src/bin/bors.rs, src/bors/event.rs, src/bors/handlers/mod.rs, src/bors/handlers/refresh.rs, src/bors/mod.rs, src/database/client.rs, src/database/operations.rs, src/tests/mocks/bors.rs
No functional changes, just renamed the global build cancellation event in anticipation of https://github.com/rust-lang/bors/issues/388, and improved logging to help debugging https://github.com/rust-lang/bors/issues/389.
=> Improve logging around build cancellation

src/bors/comment.rs, src/bors/handlers/info.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/refresh.rs, src/bors/handlers/review.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/bors/merge_queue.rs, src/database/client.rs, src/database/operations.rs, src/github/api/client.rs, src/github/api/mod.rs, src/tests/mocks/workflow.rs
There are a few places in bors where we try to cancel a pending build. Before, we used to mostly ignore cancellation errors, because we assumed that cancelling the workflows is best effort. While that is true, marking the build itself as cancelled is actually load-bearing! Because if that happens, we shouldn't continue with normal bors logic, otherwise invariants might get broken, and can get e.g. "orphaned" builds (https://github.com/rust-lang/bors/issues/389).
So we need to ideally mark the build status as cancelled first, and also distinguish an error that happens during this from the less important error that happens when external CI workflows cannot be cancelled.
While I was changing this, I also unified code for cancelling auto builds, and realized that we should not delete …
=> Handle build cancellation errors properly

src/bors/comment.rs
These are just marker conclusion jobs in rust-lang/rust, no need to show them.
Fixes things like https://github.com/rust-lang/rust/pull/144303#issuecomment-3130916214.
=> Ignore `bors build finished` failed jobs

src/bors/handlers/help.rs, src/bors/handlers/info.rs, src/bors/handlers/mod.rs, src/bors/handlers/ping.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/refresh.rs, src/bors/handlers/review.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/bors/merge_queue.rs, src/database/mod.rs, src/github/api/client.rs, src/tests/mocks/github.rs, src/tests/mocks/mod.rs, src/tests/mod.rs
Fixes: https://github.com/rust-lang/bors/issues/414
=> Hide previous try build started comment(s) on try build restart

src/bors/comment.rs, src/bors/handlers/workflow.rs, src/tests/mocks/workflow.rs
It was untested before. Also adds additional context to the error message when `min_ci_time` was triggered.
=> Add tests for `min_ci_time`

src/bin/bors.rs, src/bors/event.rs, src/bors/handlers/info.rs, src/bors/handlers/mod.rs, src/bors/handlers/pr_events.rs, src/bors/handlers/review.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs, src/bors/merge_queue.rs, src/bors/mod.rs, src/github/server.rs, src/tests/mocks/mod.rs, src/tests/mocks/pull_request.rs, src/tests/mocks/repository.rs, src/tests/mod.rs
I went through the merge queue tests to examine what they are doing. While doing that, I found a lot of suboptiomal things in the test suite API, particularly around error reporting and error handling. I ran into many deadlocks and timeouts, so I tried to make the errors from the test suite be as nice as possible.
Apart from refactoring tests, I also changed how the merge queue is executed. Now the queue is checked every 5 seconds. If there was an interesting event in the meantime, or at least 30s has elapsed since the last tick, a new tick is executed. This provides an upper bound on the merge queue execution (it won't run more than once per 5 seconds), which is useful to avoid overloading the network APIs and to handle transient errors robustly.
It is also better for tests. Before, the …
=> Refeactor merge queue tests and change how the merge queue is executed

.sqlx/query-5c3c81357e7329a9db4b2bf05c2615433b4a61c43f26f2ae39e68d02d609bf90.json, src/bors/merge_queue.rs, src/database/operations.rs
I made a big oopsie in https://github.com/rust-lang/bors/pull/433, sadly we didn't have a test covering this. This PR adds such test and fixes the query.
=> Fix merge queue PR query

src/bors/comment.rs, src/bors/handlers/trybuild.rs, src/bors/handlers/workflow.rs
It was making try build started comments unnecessarily [large](https://github.com/rust-lang/rust/pull/146595#issuecomment-3334748444).
=> Reduce space taken by workflow URLs in try build started comment

.github/workflows/test.yml, Cargo.lock
Probably renovatebot didn't update it.
=> Ensure that Cargo.lock is up-to-date on CI
